# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Version
        # https://github.com/marketplace/actions/git-semantic-version
        id: version
        uses: paulhatch/semantic-version@v5.0.2
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          major_regexp_flags: ""
          minor_pattern: "(MINOR)"
          minor_regexp_flags: ""
          bump_each_commit: false
          search_commit_body: true
          user_format_type: "csv"

      - name: Release Info
        run: |
          echo "## Changelog" > ${{ github.workspace }}-CHANGELOG.txt
          git log ${{ steps.version.outputs.previous_commit}}..${{ steps.version.outputs.current_commit}} --pretty="- %s" >> ${{ github.workspace }}-CHANGELOG.txt
          echo "" >> ${{ github.workspace }}-CHANGELOG.txt
          echo "**[Full Changelog]($GITHUB_SERVER_URL/$GITHUB_REPOSITORY/compare/${{ steps.version.outputs.previous_commit}}...${{ steps.version.outputs.current_commit}})**" >> ${{ github.workspace }}-CHANGELOG.txt
          echo "" >> ${{ github.workspace }}-CHANGELOG.txt
          echo "## Authors" >> ${{ github.workspace }}-CHANGELOG.txt
          echo "${{ steps.version.outputs.authors }}" >> ${{ github.workspace }}-CHANGELOG.txt

      - name: Debug 2
        run: |
          echo "Version tag : ${{ steps.version.outputs.version_tag }}"
          echo "Version     : ${{ steps.version.outputs.version }}"
          echo "Authors     : ${{ steps.version.outputs.authors }}"
          cat ${{ github.workspace }}-CHANGELOG.txt

      - name: Release
        # https://github.com/ncipollo/release-action
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          bodyFile: ${{ github.workspace }}-CHANGELOG.txt
          generateReleaseNotes: true
          name: Name ${{ steps.version.outputs.version }}
          tag: ${{ steps.version.outputs.version_tag }}
          draft: false
